CREATE TABLE IF NOT EXISTS weather_data (
    id INT(11) NOT NULL AUTO_INCREMENT,
    location VARCHAR(100) NOT NULL DEFAULT 'Gliwice',
    measurement_datetime DATETIME NOT NULL,
    temperature DECIMAL(5,2) NOT NULL,
    pressure DECIMAL(7,2) NOT NULL,
    humidity INT(11) NOT NULL,
    wind_speed DECIMAL(5,2) NOT NULL,
    wind_direction INT(11) DEFAULT NULL,
    rainfall DECIMAL(6,2) DEFAULT 0.00,
    snowfall DECIMAL(6,2) DEFAULT 0.00,
    visibility INT(11) DEFAULT NULL,
    uv_index DECIMAL(3,1) DEFAULT NULL,
    weather_main VARCHAR(100) DEFAULT NULL,
    weather_description VARCHAR(255) DEFAULT NULL,
    weather_icon VARCHAR(10) DEFAULT NULL,
    cloudiness INT(11) DEFAULT NULL,
    feels_like DECIMAL(5,2) DEFAULT NULL,
    sea_level_pressure DECIMAL(7,2) DEFAULT NULL,
    ground_level_pressure DECIMAL(7,2) DEFAULT NULL,
    data_source VARCHAR(50) DEFAULT 'OpenWeatherMap',
    raw_json LONGTEXT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY unique_measurement (location, measurement_datetime),
    KEY idx_datetime (measurement_datetime),
    KEY idx_temperature (temperature),
    KEY idx_created (created_at)
);
